# Generated by Django 2.2.6 on 2020-11-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
